Add files
GuilhermeVieira/library-management-api pull request #1
Opened 2020-03-31 19:09 UTC by GuilhermeVieira

2020-03-31 20:17 UTC, flpmartins88 requested changes

2020-03-31 20:17 UTC, flpmartins88 commented on src/main/kotlin/com/example/library/config/ApplicationConfiguration.kt
> +    const val USER_LOAN_LIMIT = 10
Isso aqui é especifico de uma regra de negócio, ele deveria ficar no mesmo lugar

2020-03-31 20:17 UTC, flpmartins88 commented on src/main/kotlin/com/example/library/domain/User.kt
> +        @NaturalId
Porque @NaturalId?

2020-03-31 20:17 UTC, flpmartins88 commented on src/main/kotlin/com/example/library/repository/BookRepository.kt
> +@Repository
Porque @Repository?

2020-03-31 20:17 UTC, flpmartins88 commented on src/main/kotlin/com/example/library/repository/UserRepository.kt
> +    fun findByDocumentId(documentID: String): User?
Como esse banco é gerado? Tem indice nessa coluna?

2020-03-31 20:17 UTC, flpmartins88 commented on src/main/kotlin/com/example/library/rest/exchange/BookExchange.kt
> +fun BookExchange.toDomain(): Book {
se o comando é tão simples assim, então você pode omitir o tipo de retorno e usar o igual

`fun BookExchange.toDomain() = 
   Book(....
`

2020-03-31 20:17 UTC, flpmartins88 commented on src/main/kotlin/com/example/library/rest/exchange/LoanExchange.kt
> +        @JsonProperty("user_id")
Você pode configurar isso no spring, pra usar essa estratégia de nomenclatura, isso evita de ficar usando anotações direto

2020-03-31 20:17 UTC, flpmartins88 commented on src/main/kotlin/com/example/library/service/BookService.kt
> +            ?: throw BookNotFoundException(ErrorCode.BOOK_NOT_FOUND)
Se a mensagem é sempre a mesma, pq tem que informar no parâmetro

2020-03-31 20:17 UTC, flpmartins88 commented on src/main/kotlin/com/example/library/service/UserService.kt
> +        if (userRepository.findByDocumentId(documentId) == null) {
Essa lógica pode ser simplificada, já que o retorno é boleano

2020-03-31 20:17 UTC, flpmartins88 commented on src/main/kotlin/com/example/library/service/UserService.kt
> +        if (documentIdExists(user.documentId)) {
takeIf { userExists }?.let { save } ?: erro

2020-03-31 20:17 UTC, flpmartins88 commented on src/test/kotlin/com/example/library/rest/BookControllerTest.kt
> +                .andExpect(jsonPath("title").value(BOOK_TITLE))
Aqui é legal fazer igual ao de baixo, sem essas constantes

2020-04-01 14:29 UTC, GuilhermeVieira commented on src/main/kotlin/com/example/library/domain/User.kt
> +        @NaturalId
Porque o `documentId` é um unique identifier no mundo real. A documentação do Hibernate recomenda o uso de surrogate keys, mas diz que é últil anotar com `@NaturalId `pois ele consegue deixar o carregamento das entities mais eficiente quando as queries são feitas pelos natural id's.

2020-04-01 14:29 UTC, GuilhermeVieira commented on src/main/kotlin/com/example/library/repository/BookRepository.kt
> +@Repository
Eu testei e não é necessário. Eu segui o JpaRepository e ele estende a interface `Repository<T, ID>` predefinida. Então eu sou uso a `@Repository` se eu for realmente implementar as queries.

2020-04-01 14:57 UTC, GuilhermeVieira commented on src/main/kotlin/com/example/library/repository/UserRepository.kt
> +    fun findByDocumentId(documentID: String): User?
Eu não entendi a pergunta. Mas pela pergunta ser sobre ter índice eu acredito que o questionamento seja sobre performance da busca. No domain eu defini como `@NaturalId` o campo `documentId` e pelo o que eu li na documentação eu acho que isso eficiente.

2020-04-01 17:02 UTC, flpmartins88 commented on src/main/kotlin/com/example/library/domain/User.kt
> +        @NaturalId
sim, mas pra fazer isso vc tem que fazer session.algumaCoisaNaturalId() e esse método é do Hibernate, não temos no JPA

2020-04-01 17:03 UTC, flpmartins88 commented on src/main/kotlin/com/example/library/repository/BookRepository.kt
> +@Repository
Essa anotação só vai nas classes concretas, nas interfaces que são usadas já existe

2020-04-01 17:03 UTC, flpmartins88 commented on src/main/kotlin/com/example/library/repository/UserRepository.kt
> +    fun findByDocumentId(documentID: String): User?
Mesmo assim precisa criar indice pra ela, ele não sabe como foi definida.

2020-04-09 16:30 UTC, DaniloDainez commented on src/main/kotlin/com/example/library/exception/Exceptions.kt
> +class UserReachedLoanLimitException(override val message: String = ErrorCode.USER_REACHED_LOAN_LIMIT): BadRequestException()
Não acho q seja um caso de bad request, pois o usuário nao passou nada de incorreto no payload, ele simplesmente nao está autorizado a emprestar um livro

2020-04-09 16:32 UTC, DaniloDainez commented on src/main/kotlin/com/example/library/rest/exchange/LoanExchange.kt
> +fun List<Loan>.toLoanExchange() = this.map { it.toLoanExchange() }
boa!

2020-04-09 21:53 UTC, flpmartins88 reviewed
Fecha um pacote na PR, conserta as considerações que vc achar válida e mergeia.

As novas coisas vc vai faz em outra PR, isso facilita o review.

Evite PRs grandes, geralmente um feature por PR.

2020-04-09 21:53 UTC, flpmartins88 commented on src/test/kotlin/com/example/library/service/LoanServiceTest.kt
> +            every { loanService["isBookAvailable"](book.id) } returns true
Nunca tinha  visto essa sintaxe de invocação de método. Mas esse tipo de coisa não fica muito legal, não sei como o kotlin trabalharia, mas ele pode fazer assert na invocação e pode ser um pouco mais lento.

Você tbm perde toda a praticidade das validações que as IDEs te dão, esse método só deve ser avaliado em tempo de execução, então se vc escrever errado ou esquecer dele em uma refatoração vai dar problema.

2020-04-09 21:53 UTC, flpmartins88 commented on src/test/kotlin/com/example/library/rest/BaseControllerTest.kt
> +        return objectMapper.readValue(mockMvc.perform(post("/users")
Cuidado com a quantidade de operações que você faz em um mesmo comando.

Fica dificil de ler.

Nessa função vc tem 5 operações acontecendo:
- Você cria um objeto usuário
- Você transforma o usuário em json
- Você envia para o sistema para cadastrar
-  você pega a resposta do sistema
- e por último, transforma o corpo da requisição em um objeto

As vezes separar parece que deixa o código amador, mas o melhor código é aquele que você bate o olho e já consegue dizer o que está acontecendo

2020-04-09 21:53 UTC, flpmartins88 commented on src/test/kotlin/com/example/library/rest/BookControllerTest.kt
> +        val bookRequest = buildBookRequest()
Se seus testes tem pré requisitos iguais ou semelhantes, você pode usar anotações como @Before e a @After

Elas são executadas antes e depois de cada teste.

Mas o mais importante dos testes é que um teste não deve influenciar em outro. Todos eles devem funcionar execurando em qualquer ordem, quantidade ou repetições;

2020-04-09 21:53 UTC, flpmartins88 commented on src/test/kotlin/com/example/library/rest/LoanControllerTest.kt
> +                .andExpect(status().isBadRequest)
Aqui vale validar qual é a mensagem de erro que vai para o usuário, só validar o badrequest deixa o teste um pouco inútil, já que o badrequest pode acontecer de várias maneiras.

2020-04-09 21:53 UTC, flpmartins88 commented on src/main/kotlin/com/example/library/domain/Loan.kt
> +        var status: FineStatus?
Aqui já não valeria a pena deixar inicializado? Assim vocÊ evitaria o null.

2020-04-09 21:53 UTC, flpmartins88 commented on src/main/kotlin/com/example/library/service/BookService.kt
> +class BookService(val bookRepository: BookRepository) {
sempre que você usar a injeção de dependencia no kotlin, coloca os componentes/serviços como privado.

O kotlin por padrão vai gerar a propriedade para esse cara e ele vai ser acessível por esse serviço

Exemplo: bookService.bookRepository.qualquercoisa(...) <- quem tiver acesso ao bookService vai poder fazer qualquer coisa com o repositório

2020-04-09 21:53 UTC, flpmartins88 commented on src/main/kotlin/com/example/library/service/LoanService.kt
> +    val finePerDay = 2.0
Para esses valores fixos assim prefira sempre usar constantes e na nomenclatura tbm

2020-04-09 21:53 UTC, flpmartins88 commented on src/main/kotlin/com/example/library/domain/Book.kt
> +        val id: String = UUID.randomUUID().toString().toUpperCase(),
O problema de iniciar UUIDs na inicialização do projeto é que o UUID vai ficando escasso e uma hora fica na loteria de que dá duplicidade ou atualiza o registro errado.

O melhor modo é usar o generators do hibernate, existe uma estrutura que se dá erro de duplicidade de id, vc consegue falar pra ele gerar outro id para usar no lugar.

Mas como é um projeto de teste está de bom tamanho.

2020-04-09 21:53 UTC, flpmartins88 commented on src/main/kotlin/com/example/library/repository/BookRepository.kt
> +interface BookRepository: JpaRepository<Book, String>
Só um detalhe, na herança ou implementação o simbolo ":" tem espaço dos dois lados

2020-04-09 21:53 UTC, flpmartins88 commented on src/main/kotlin/com/example/library/rest/ExceptionHandler.kt
> +        logger.warn("Returning HTTP " + status.toString() +
em vez de ficar concatenando, vc pode usar a interpolação de string do kotlin para montar a mensagem.

2020-04-13 13:43 UTC, GuilhermeVieira commented on src/main/kotlin/com/example/library/exception/Exceptions.kt
> +class UserReachedLoanLimitException(override val message: String = ErrorCode.USER_REACHED_LOAN_LIMIT): BadRequestException()
Vou mudar para Forbidden, acredito que seja o status code mais adequado, já que o request está certo e o cliente tem credenciais, mas só não pode completar o request por falta de algum tipo de permissão.

2020-04-13 13:51 UTC, GuilhermeVieira commented on src/test/kotlin/com/example/library/service/LoanServiceTest.kt
> +            every { loanService["isBookAvailable"](book.id) } returns true
Essa sintaxe serve para mockar métodos privados. Mas depois eu resolvi deixar esses métodos públicos. 

Eu também notei que precisar mockar um método privado seja um índicio que esse método não devesse ser privado. Li em algum lugar que os métodos privados tem que ser simples o bastante para serem testados pelos testes dos métodos que os invocam.

2020-04-13 14:11 UTC, DaniloDainez requested changes

2020-04-13 14:11 UTC, DaniloDainez commented on src/main/kotlin/com/example/library/service/LoanService.kt
> +    val finePerDay = 2.0
Acredito que essas variáveis devam ser constantes, além disso o nome das variáveis não me diz em qual unidade de medida elas estão. Quando se trata de questões monetárias, geralmente utilizamos os valores em centavos para evitar problemas de perda de precisão nas operações com dinheiro.

2020-04-13 14:11 UTC, DaniloDainez commented on src/main/kotlin/com/example/library/service/LoanService.kt
> +    fun close(loan: Loan): Loan {
Acho q closeLoan seria um nome mais descritivo pra essa função.

2020-04-13 14:11 UTC, DaniloDainez commented on src/main/kotlin/com/example/library/service/LoanService.kt
> +class LoanService(val loanRepository: LoanRepository,
Acredito que algumas funções dessa classe poderiam ser privadas e não são, favor verificar. Só nao te falo o nome exato das funções pq nao sei revisar pr direito no github rsrsrs

2020-04-13 14:11 UTC, DaniloDainez commented on src/main/kotlin/com/example/library/service/UserService.kt
> +    private fun userExists(user: User) =
O nome dessa função está errado, ela retorna se um usuário **não** existe. Em questao de boas práticas não é legal vc ter funções booleanas negadas como userDoesNotExist pq ai quando vc vai fazer operações de lógica booleana com o retorno dessas funções fica confuso. Devido a isso, minha sugstão é vc manter o nome da função do jeito q ta e trocar a condição pra != null, ai vc nega ela na função create.

2020-04-13 16:56 UTC, GuilhermeVieira commented on src/main/kotlin/com/example/library/domain/Loan.kt
> +        var status: FineStatus?
Eu tinha feito de um jeito na qual a propriedade fine em um Loan era sempre inicializada com valor 0.0 e status NOT_CHARGED, só que isso não representa muito bem o domínio real do meu problema, nem todo empréstimo tem uma multa. 

Essa data class Fine não pode ser inicializada com um valor padrão porque dá um pau no banco de dados, acredito que seja pelo fato de Fine ser um embeddable type nullable no Loan. Como seus atributos não são nullable, se eu fosse o banco nem saberia como guardar algo que tem que ser nullable e tem que ser inicializado ao mesmo tempo.

2020-04-14 02:34 UTC, flpmartins88 commented on src/main/kotlin/com/example/library/rest/ExceptionHandler.kt
> +            handleGenericException(exception, request, HttpStatus.FORBIDDEN)
O Forbidden diz respeito a autorização/autenticação, não uma proibição de uso por uma lógica.

https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status/403

2020-04-15 20:08 UTC, merged